### PR TITLE
Add initial support of UID and GID

### LINKED ISSUE #9: Implement userdefined UID ang GID for shell
Since Docker is using different methods to share files between host and container, it may be required to set `UID` and `GID` of ZSH when you need to update files from your containers.

https://www.reddit.com/r/docker/comments/jh9qyt/inconsistent_behaviour_with_permissions_of_a_bind/

Idea is to create a user named `avd` with preconfigure shell and `uid=1000` / `gid=1000`. 

```Dockerfile
[...]
RUN useradd -md /home/avd -s /bin/zsh -u 1000 avd
USER avd

# Install Oh My ZSH to provide improved shell
RUN wget --quiet https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true \
    && echo 'plugins=(ansible common-aliases safe-paste git jsontools history git-extras)' >> $HOME/.zshrc \
    && echo 'eval `ssh-agent -s`' >> $HOME/.zshrc \
    && echo 'export TERM=xterm' >>  $HOME/.zshrc

# Set default folder
WORKDIR /projects
VOLUME ["/projects"]

# Use ZSH as default shell with default oh-my-zsh theme
ENV PATH=$PATH:/root/.local/bin
USER root
CMD [ "/bin/entrypoint.sh" ]
```

Entrypoint will implement support for custom value:

```bash
# Reconfigure AVD User id if set by user
if [ ! -z "${AVD_UID}" ]; then
  echo "Update uid for user avd with ${AVD_UID}"
  usermod -u ${AVD_UID} avd
fi

if [ ! -z "${AVD_GID}" ]; then
  echo "Update gid for group avd with ${AVD_GID}"
  groupmod -g ${AVD_GID} avd
fi

su - avd -c /bin/zsh
```

PR coming shortly

### PR DESCRIPTION
**Pull request by titom73**
Fixes #9 

## Issue summary

Since Docker is using different methods to share files between host and container, it may be required to set `UID` and `GID` of ZSH when you need to update files from your containers.

https://www.reddit.com/r/docker/comments/jh9qyt/inconsistent_behaviour_with_permissions_of_a_bind/

## Summary

Idea is to create a user named `avd` with preconfigure shell and `uid=1000` / `gid=1000`. 

```Dockerfile
[...]
RUN useradd -md /home/avd -s /bin/zsh -u 1000 avd
USER avd

# Install Oh My ZSH to provide improved shell
RUN wget --quiet https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh || true \
    && echo 'plugins=(ansible common-aliases safe-paste git jsontools history git-extras)' >> $HOME/.zshrc \
    && echo 'eval `ssh-agent -s`' >> $HOME/.zshrc \
    && echo 'export TERM=xterm' >>  $HOME/.zshrc

# Set default folder
WORKDIR /projects
VOLUME ["/projects"]

# Use ZSH as default shell with default oh-my-zsh theme
ENV PATH=$PATH:/root/.local/bin
USER root
CMD [ "/bin/entrypoint.sh" ]
```

Entrypoint will implement support for custom value:

```bash
# Reconfigure AVD User id if set by user
if [ ! -z "${AVD_UID}" ]; then
  echo "Update uid for user avd with ${AVD_UID}"
  usermod -u ${AVD_UID} avd
fi

if [ ! -z "${AVD_GID}" ]; then
  echo "Update gid for group avd with ${AVD_GID}"
  groupmod -g ${AVD_GID} avd
fi

su - avd -c /bin/zsh
```

## Usage

```bash
❯ id
uid=501(titom73) gid=20(staff)

❯ docker run --rm -it -v ./docker-avd-base/:/projects \
	-e AVD_REQUIREMENTS=NONE \
	-e AVD_ANSIBLE= \
	-e AVD_UID=1001 \
	-e AVD_GID=1001 \
	-v /etc/hosts:/etc/hosts avdteam/base:3.6-feature-uid

Requirement file not found, skipping...
Update uid for user avd with 1001
Update gid for group avd with 1001
Agent pid 53
➜  /projects git:(feature-uid) id
uid=1001(avd) gid=1001(avd) groups=1001(avd)
```

### CODE REVIEW

**Comment by ryanmerolle** [comment]
This is a better approach than how I first tackled in my own work netdev containers.  I was instead experimenting with having the user build the image adding the uid that way.  Entrypoint is a way better option that handles everything behind the scenes.

**Comment by ryanmerolle** [comment]
I tested and all looks good.  The avd uid/gid map correctly and the volume file permission issues on the host WSL or Linux system are no longer seen.  Furthermore, as expected, the user `avd` is not shown when inspecting the file permissions, but instead the matching username to the uid is displayed from the host system.

I do not see any risk in setting the default vars for GID and UID to use $(id -g) and $(id -u) since mac users would not be impacted negatively.  Asking the user to pass `make run UID=$(id -u) GID=$(id -g)` is likely adding a undue barrier for getting started.

I noticed that when I connected using the make command above, I was no longer being placed into the projects directory at first log in.

**Comment by titom73** [comment]
A temporary image is available for testing:

```bash
$ docker pull avdteam/base:3.6-feature-uid
```

Updates:
---------

- Start in `projects` folder
- Tested with AVD playbook
- Readme updated

Known Limitations:
-------------------

- Cannot assign `uid` or `gid` if already configured in container

**Comment by ryanmerolle** [comment]
`docker pull avdteam/base:3.6-feature-uid` is missing `/bin/entrypoint.sh`  If I build the image locally, I see it just fine.  Because of this, the image tag for this feature that you can pull  from dockerhub does not work properly.  Just an FYI if you want to use that tag.  I am not sure how to view your github actions settings, but I suspect it is still building off of master which does not have an entrypoint.sh copied to /bin.

**Comment by ryanmerolle** [comment]
Another observation.  Assuming you build the feature-uid locally, when using with .devcontainers, the entrypoint.sh does not execute it seems to be overwritten by VS code.

When using the below devcontainer.json (swapping the image out from `3.6` to `3.6-feature-uid`, root is always the connected user instead of avd for the new `3.6-feature-uid`

```
{
  "name": "AVD_development",
  "image": "avdteam/base:3.6-feature-uid",

  "settings": {
      "terminal.integrated.shell.linux": "/bin/zsh",
  },

//"extensions": [
//     "ms-python.python",
//],
  "containerEnv": {
      "ANSIBLE_CONFIG": "./ansible.cfg"
  }
}
```

Example:
```
16b1c8a42390# whoami
root

16b1c8a42390# /bin/entrypoint.sh 
Agent pid 317

➜  /projects whoami
avd
```

https://code.visualstudio.com/docs/remote/devcontainerjson-reference#_devcontainerjson-properties

I suspect this is because:

overrideCommand | boolean | Tells VS Code whether it should run /bin/sh -c "while sleep 1000; do :; done" when starting the container instead of the container's default command. Defaults to true since the container can shut down if the default command fails. Set to false if the default command must run for the container to function properly.
-- | -- | --


With the original version of this Dockerfile that did not leverage entrypoint.sh as extensively as this build.  Hence why it works with the above devcontainer.json vs the new build using the same devcontainer.json with the new image.

Possibly not tied to this PR, but we should look to play around with the `devcontainer.json` settings to fix this.  I tried various combinations of `overrideCommand`,  `postCreateCommand`, `postStartCommand`, `postAttachCommand`.

In nearly all instances where I pointed a post command to /bin/entrypoint.sh, the container hung during startup in vscode.  When disabling the overrideCommand, docker in vs Code would error out.

**Comment by titom73** [comment]
Indeed, VScode is not using `entrypoint` nor `cmd` defined at image level

1. Container startup

```shell
[115330 ms] Start: Run: docker run -a STDOUT -a STDERR \
--mount type=bind,source=arista-ansible,target=/workspaces/\
arista-ansible,consistency=cached -l vsch.quality=stable \
-l vsch.remote.devPort=0 -l vsch.local.folder=arista-ansible \
-e ANSIBLE_CONFIG=./ansible.cfg --entrypoint /bin/sh vsc-arista-\
ansible-b3cc758e689c9e9bf6a9db85407b3e11 -c echo Container started ; \
trap "exit 0" 15; while sleep 1 & wait $!; do :; done
Container started
```

2. Container configuration

```
docker exec -i -u root -e \
VSCODE_REMOTE_CONTAINERS_SESSION=92a54d52-\
c6ec-4491-a322-19c1e99b33ce1605722417727 d76d69272b979d4d092160382b1d7202e21bb3f4ecf3af63537396280ba75427\
/bin/sh
```

**Comment by ryanmerolle** [comment]
devcontainer.json fix:
```
{
  "name": "AVD_development",
  "image": "avdteam/base:3.6-feature-uid",
  "remoteUser": "avd",
  "updateRemoteUserUID": true,
  "settings": {
      "terminal.integrated.shell.linux": "/bin/zsh",
  },

//"extensions": [
//     "ms-python.python",
//],
  "containerEnv": {
      "ANSIBLE_CONFIG": "./ansible.cfg"
  }
}
```

I will update the documentation and look into the same for docker-compose version.  Thanks @titom73

**Pull request merged**
